export const MISSING_ACCENT_MAP = {
  voce: 'você',
  esta: 'está',
  nao: 'não',
  ate: 'até',
  atraves: 'através',
  facil: 'fácil',
  dificil: 'difícil',
  possivel: 'possível',
  impossivel: 'impossível',
  agua: 'água',
  ultimo: 'último',
  ultima: 'última',
  proximo: 'próximo',
  proxima: 'próxima',
  unico: 'único',
  unica: 'única',
  historia: 'história',
  memoria: 'memória',
  familia: 'família',
  necessario: 'necessário',
  necessaria: 'necessária',
  facilmente: 'facilmente',
  ninguem: 'ninguém',
  alguem: 'alguém',
  tambem: 'também',
  porem: 'porém',
  razao: 'razão',
  coracao: 'coração',
  emocao: 'emoção',
  paixao: 'paixão',
  situacao: 'situação',
  atencao: 'atenção',
  estacao: 'estação',
  sera: 'será',
  serao: 'serão',
  havera: 'haverá',
  pais: 'país',
  saude: 'saúde',
  juizo: 'juízo',
  saida: 'saída',
  sabia: 'sábia',
  sabio: 'sábio',
  varios: 'vários',
  varias: 'várias',
  contrario: 'contrário',
  diario: 'diário',
  obrigatorio: 'obrigatório',
  territorio: 'território',
  silencio: 'silêncio',
  orgulho: 'orgulho',
  solidao: 'solidão',
  saudade: 'saudade',
  lagrima: 'lágrima',
  amanha: 'amanhã',
  orfao: 'órfão',
  orgao: 'órgão',
  album: 'álbum',
  agil: 'ágil',
  fragil: 'frágil',
  publico: 'público',
  imovel: 'imóvel',
  movel: 'móvel',
  arvore: 'árvore',
  rapido: 'rápido',
  maximo: 'máximo',
  minimo: 'mínimo',
  otimo: 'ótimo',
  pessimo: 'péssimo',
  regua: 'régua',
  genero: 'gênero',
  numero: 'número',
  epoca: 'época',
  regiao: 'região',
  religiao: 'religião',
  opiniao: 'opinião',
  reuniao: 'reunião',
  televisao: 'televisão',
};

export const CONFUSABLE_PAIRS = [
  { words: ['mas', 'mais'], hint: '"mas" é oposição (porém); "mais" é quantidade.' },
  { words: ['porque', 'por que', 'porquê', 'por quê'], hint: '"porque" explica; "por que" pergunta; "porquê" é substantivo; "por quê" no fim da frase.' },
  { words: ['mau', 'mal'], hint: '"mau" é adjetivo (oposto de bom); "mal" é advérbio (oposto de bem) ou substantivo.' },
  { words: ['ao encontro', 'de encontro'], hint: '"ao encontro de" é a favor; "de encontro a" é contra, colisão.' },
  { words: ['tampouco', 'tão pouco'], hint: '"tampouco" é também não; "tão pouco" é intensidade.' },
  { words: ['a fim de', 'afim'], hint: '"a fim de" é finalidade; "afim" é semelhança, afinidade.' },
  { words: ['onde', 'aonde'], hint: '"onde" é lugar fixo; "aonde" indica movimento.' },
  { words: ['sessão', 'seção', 'cessão'], hint: '"sessão" é reunião ou período; "seção" é divisão; "cessão" é ceder algo.' },
  { words: ['iminente', 'eminente'], hint: '"iminente" é prestes a acontecer; "eminente" é notável, destacado.' },
];

export function findAccentMistakes(text) {
  const results = [];
  const wordRegex = /\p{L}+/gu;
  let match;
  while ((match = wordRegex.exec(text)) !== null) {
    const word = match[0];
    const lower = word.toLowerCase();
    if (MISSING_ACCENT_MAP[lower]) {
      results.push({
        word,
        index: match.index,
        length: word.length,
        suggestion: MISSING_ACCENT_MAP[lower],
        type: 'acento',
      });
    }
  }
  return results;
}
