import {useEffect,useMemo,useState}from'react';import{Link,useParams}from'react-router-dom';import{api}from'../lib/api';import{useAuth}from'../hooks/useAuth.jsx';import'../components/StoryBible.css';import'./BookLore.css';
const TL={character:'Personagem',object:'Objeto'};
export default function WhereIsIt({writer=false}){const params=useParams(),{user}=useAuth();const[books,setBooks]=useState([]),[bookId,setBookId]=useState(params.bookId||''),[data,setData]=useState(null),[chapterId,setChapterId]=useState('');const slug=params.slug;
 useEffect(()=>{if(writer){api.writerBooks().then(d=>{setBooks(d.books);if(!bookId&&d.books[0])setBookId(String(d.books[0].id))})}},[writer]);
 useEffect(()=>{if(writer&&bookId)api.writerStoryBible(bookId).then(d=>{setData(d);if(!chapterId&&d.chapters[0])setChapterId(String(d.chapters[0].id))});else if(!writer&&slug)api.bookStoryBible(slug).then(d=>{setData(d);if(!chapterId&&d.chapters.at(-1))setChapterId(String(d.chapters.at(-1).id))})},[writer,bookId,slug]);
 const trackable=(data?.entities||[]).filter(e=>e.type==='character'||e.type==='object'), places=(data?.entities||[]).filter(e=>e.type==='place');const current=useMemo(()=>{const selected=data?.chapters?.find(c=>String(c.id)===String(chapterId));const m=new Map();if(!selected)return m;for(const x of (data?.locations||[]).filter(x=>Number(x.chapter_order)<=Number(selected.order_index)).sort((a,b)=>Number(a.chapter_order)-Number(b.chapter_order))){m.set(`${x.entity_type}:${x.entity_id}`,x)}return m},[data,chapterId]);
 async function save(entity,place,note){await api.setLoreLocation(bookId,{chapter_id:Number(chapterId),entity_type:entity.type,entity_id:entity.id,place_id:place?Number(place):null,location_note:note});setData(await api.writerStoryBible(bookId))}
 if(!data&&(!writer||bookId))return null;return <div className={writer?'lore-page':'book-lore-page'}>{!writer&&<Link className="book-lore-back" to={`/biblioteca/${slug}`}>Voltar ao livro</Link>}<h1 className={writer?'lore-title':'book-lore-title'}>Onde se localiza</h1><p className="lore-appearance-hint">Um retrato do universo em cada capitulo: quem esta onde e onde cada objeto importante ficou.</p>
 <div className="location-toolbar">{writer&&<select value={bookId} onChange={e=>{setBookId(e.target.value);setChapterId('')}}>{books.map(b=><option key={b.id} value={b.id}>{b.title}</option>)}</select>}<select value={chapterId} onChange={e=>setChapterId(e.target.value)}><option value="">Escolha um capitulo</option>{data?.chapters.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select>{!writer&&user?.role!=='escritor'&&<small>So aparecem capitulos que voce ja concluiu.</small>}</div>
 {chapterId&&<div className="location-grid">{trackable.map(e=>{const loc=current.get(`${e.type}:${e.id}`);return writer?<LocationEdit key={`${e.type}:${e.id}`} entity={e} places={places} loc={loc} onSave={save}/>:<div className="location-row" key={`${e.type}:${e.id}`}><div className="location-entity"><small>{TL[e.type]}</small><strong>{e.name}</strong></div><strong>{loc?.place_name||'Local desconhecido'}</strong><span>{loc?.location_note||''}</span></div>})}</div>}</div>}
function LocationEdit({entity,places,loc,onSave}){const[place,setPlace]=useState(loc?.place_id||''),[note,setNote]=useState(loc?.location_note||'');useEffect(()=>{setPlace(loc?.place_id||'');setNote(loc?.location_note||'')},[loc?.place_id,loc?.location_note]);return <div className="location-row"><div className="location-entity"><small>{TL[entity.type]}</small><strong>{entity.name}</strong></div><select value={place} onChange={e=>setPlace(e.target.value)}><option value="">Local desconhecido</option>{places.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input value={note} onChange={e=>setNote(e.target.value)} placeholder="ex.: ala norte, escondido no cofre..." maxLength={500}/><button onClick={()=>onSave(entity,place,note)}>Salvar</button></div>}
